name: Deploy Portfolio 

on: 
    push:
        branches:
            - main
        paths:
            - "portfolio/**"

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: checkout repository
              uses: actions/checkout@v4

            - name: Azure Login
              uses: azure/login@v3
              with:
                creds: |
                    {
                        "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
                        "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
                        "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
                        "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
                    }
            - name: Sync portfolio files to Blob Storage
              run: |
                az storage blob sync \
                --account-name productioncontainerweb \
                --container '$web' \
                --source portfolio \
                --delete-destination true \

            - name: Purge Front Door cache
              run: |
                az config set extension.use_dynamic_install=yes_without_prompt
                az config set extension.dynamic_install_allow_preview=true
                az afd endpoint purge \
                --resource-group static-web-production-rg \
                --profile-name portfolio-frontdoor-profile \
                --endpoint-name portfolio-frontdoor-endpoint \
                --content-paths "/*"
