name: Terraform CI

on: 
    push:
        branches:
            - main
    
    pull_request:
        branches:
            - main

jobs:
    terraform:
        runs-on: ubuntu-latest

        steps:
            - name: checkout repository
              uses: actions/checkout@v4
